/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 supplement.glb 
*/

import { useGLTF } from "@react-three/drei";
import { motion } from "framer-motion-3d";
import React from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/supplement.glb");
  const { section } = props;
  return (
    <motion.group
      animate={{
        rotateY: section === 0 ? 6 : 1,
      }}
      {...props}
      dispose={null}
    >
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.Glass}
        position={[0, 0.01, 0]}
        scale={[0.288, 0.423, 0.288]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.Lid}
        position={[0, 0.676, 0]}
        scale={[0.24, 0.09, 0.24]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials["Material.005"]}
        position={[0, 0.018, 0]}
        scale={[0.289, 0.34, 0.289]}
      />
    </motion.group>
  );
}

useGLTF.preload("/supplement.glb");
